version: '2'
services:
    gptrobot:
        volumes:
            - './config:/GPT/config'
            - './logs:/GPT/logs'
        environment:
            - WS_URL=ws://<改成你配置的URL>
            - HTTP_URL=http://<改成你配置的URL>
        container_name: gptrobot
        restart: always
        image: 'pairzhu/gptrobot'