version: '2'
services:
    gpt3robot:
        volumes:
            - './config:/root/GPT3/config'
            - './logs:/root/GPT3/logs'
        environment:
            - WS_URL=ws://<改成你配置的URL>
            - HTTP_URL=http://<改成你配置的URL>
        container_name: gpt3robot
        restart: always
        image: 'pairzhu/gpt3cqrobot'